app:
  title: This is Spring Cloud Application at the PRODUCTION env
  timeout: 10000
  db:
    host: postgres-server
    password: postgres12345

#spring:
#  rabbitmq:
#    host: rabbitmq-host
#    password: xxx
