###
# Этот сервис первичен - остальные от него уже зависят
#
server.port: 8761 # Порт по умолчанию для Eureka Server

# app id
spring.application.name: eureka-server

eureka:
  #hostname: eureka-server-1 # Имя хоста для этого экземпляра Eureka Server
  instance.hostname: localhost
  client:
    register-with-eureka: false # no need to register itself
    fetch-registry: false # no need to look for the registry
    serviceUrl:
     #defaultZone: http://eureka-server-2:8762/eureka/ # Где будет регистрироваться (в другом сервере)
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always

logging:
  level:
    root: INFO # Базовый уровень для всего приложения
    com.netflix.eureka: DEBUG # Установить уровень DEBUG для логирования Eureka Server
    com.netflix.discovery: DEBUG # Установить уровень DEBUG для логирования Discovery
    org.springframework.cloud.netflix.eureka: DEBUG # Для специфичных логов Spring Cloud Netflix Eureka
    # org.springframework.cloud: DEBUG # Можно включить, если нужно больше логов от Spring Cloud в целом